<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()>
Partial Class settingsView
    Inherits DevExpress.XtraEditors.XtraUserControl

    'UserControl overrides dispose to clean up the component list.
    <System.Diagnostics.DebuggerNonUserCode()>
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        If disposing AndAlso components IsNot Nothing Then
            components.Dispose()
        End If
        MyBase.Dispose(disposing)
    End Sub

    'Required by the Windows Form Designer
    Private components As System.ComponentModel.IContainer

    'NOTE: The following procedure is required by the Windows Form Designer
    'It can be modified using the Windows Form Designer.  
    'Do not modify it using the code editor.
    <System.Diagnostics.DebuggerStepThrough()>
    Private Sub InitializeComponent()
        Dim WindowsUIButtonImageOptions6 As DevExpress.XtraBars.Docking2010.WindowsUIButtonImageOptions = New DevExpress.XtraBars.Docking2010.WindowsUIButtonImageOptions()
        Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(settingsView))
        Dim WindowsUIButtonImageOptions7 As DevExpress.XtraBars.Docking2010.WindowsUIButtonImageOptions = New DevExpress.XtraBars.Docking2010.WindowsUIButtonImageOptions()
        Dim WindowsUIButtonImageOptions8 As DevExpress.XtraBars.Docking2010.WindowsUIButtonImageOptions = New DevExpress.XtraBars.Docking2010.WindowsUIButtonImageOptions()
        Dim WindowsUIButtonImageOptions9 As DevExpress.XtraBars.Docking2010.WindowsUIButtonImageOptions = New DevExpress.XtraBars.Docking2010.WindowsUIButtonImageOptions()
        Dim WindowsUIButtonImageOptions10 As DevExpress.XtraBars.Docking2010.WindowsUIButtonImageOptions = New DevExpress.XtraBars.Docking2010.WindowsUIButtonImageOptions()
        Me.windowsUIButtonPanelMain = New DevExpress.XtraBars.Docking2010.WindowsUIButtonPanel()
        Me.NavigationFrame1 = New DevExpress.XtraBars.Navigation.NavigationFrame()
        Me.NavigationPage1 = New DevExpress.XtraBars.Navigation.NavigationPage()
        Me.LayoutControl1 = New DevExpress.XtraLayout.LayoutControl()
        Me.sch_name_tb = New DevExpress.XtraEditors.TextEdit()
        Me.sch_address_tb = New DevExpress.XtraEditors.MemoEdit()
        Me.sch_motto_tb = New DevExpress.XtraEditors.TextEdit()
        Me.sch_email_tb = New DevExpress.XtraEditors.TextEdit()
        Me.sch_contact_no_tb = New DevExpress.XtraEditors.TextEdit()
        Me.sch_logo_picedit = New DevExpress.XtraEditors.PictureEdit()
        Me.SimpleButton1 = New DevExpress.XtraEditors.SimpleButton()
        Me.sch_website_tb = New DevExpress.XtraEditors.TextEdit()
        Me.Sch_facebook_tb = New DevExpress.XtraEditors.TextEdit()
        Me.sch_twitter_tb = New DevExpress.XtraEditors.TextEdit()
        Me.sch_linkedIn_tb = New DevExpress.XtraEditors.TextEdit()
        Me.LayoutControlGroup1 = New DevExpress.XtraLayout.LayoutControlGroup()
        Me.Root1 = New DevExpress.XtraLayout.LayoutControlGroup()
        Me.Root2 = New DevExpress.XtraLayout.LayoutControlGroup()
        Me.Root3 = New DevExpress.XtraLayout.LayoutControlGroup()
        Me.LayoutControlItem2 = New DevExpress.XtraLayout.LayoutControlItem()
        Me.LayoutControlItem5 = New DevExpress.XtraLayout.LayoutControlItem()
        Me.LayoutControlItem10 = New DevExpress.XtraLayout.LayoutControlItem()
        Me.LayoutControlItem12 = New DevExpress.XtraLayout.LayoutControlItem()
        Me.EmptySpaceItem4 = New DevExpress.XtraLayout.EmptySpaceItem()
        Me.LayoutControlItem13 = New DevExpress.XtraLayout.LayoutControlItem()
        Me.EmptySpaceItem5 = New DevExpress.XtraLayout.EmptySpaceItem()
        Me.EmptySpaceItem19 = New DevExpress.XtraLayout.EmptySpaceItem()
        Me.EmptySpaceItem20 = New DevExpress.XtraLayout.EmptySpaceItem()
        Me.EmptySpaceItem21 = New DevExpress.XtraLayout.EmptySpaceItem()
        Me.LayoutControlItem4 = New DevExpress.XtraLayout.LayoutControlItem()
        Me.LayoutControlItem3 = New DevExpress.XtraLayout.LayoutControlItem()
        Me.Root4 = New DevExpress.XtraLayout.LayoutControlGroup()
        Me.Root5 = New DevExpress.XtraLayout.LayoutControlGroup()
        Me.Root6 = New DevExpress.XtraLayout.LayoutControlGroup()
        Me.LayoutControlItem7 = New DevExpress.XtraLayout.LayoutControlItem()
        Me.LayoutControlItem9 = New DevExpress.XtraLayout.LayoutControlItem()
        Me.LayoutControlItem11 = New DevExpress.XtraLayout.LayoutControlItem()
        Me.LayoutControlItem14 = New DevExpress.XtraLayout.LayoutControlItem()
        Me.EmptySpaceItem8 = New DevExpress.XtraLayout.EmptySpaceItem()
        Me.autoGeneratedGroup1 = New DevExpress.XtraLayout.LayoutControlGroup()
        Me.EmptySpaceItem2 = New DevExpress.XtraLayout.EmptySpaceItem()
        Me.autoGeneratedGroup0 = New DevExpress.XtraLayout.LayoutControlGroup()
        Me.EmptySpaceItem7 = New DevExpress.XtraLayout.EmptySpaceItem()
        Me.EmptySpaceItem1 = New DevExpress.XtraLayout.EmptySpaceItem()
        Me.EmptySpaceItem3 = New DevExpress.XtraLayout.EmptySpaceItem()
        Me.EmptySpaceItem6 = New DevExpress.XtraLayout.EmptySpaceItem()
        Me.NavigationPage2 = New DevExpress.XtraBars.Navigation.NavigationPage()
        Me.LayoutControl2 = New DevExpress.XtraLayout.LayoutControl()
        Me.GroupControl3 = New DevExpress.XtraEditors.GroupControl()
        Me.LayoutControl4 = New DevExpress.XtraLayout.LayoutControl()
        Me.idNoInitial = New DevExpress.XtraEditors.TextEdit()
        Me.LayoutControlGroup4 = New DevExpress.XtraLayout.LayoutControlGroup()
        Me.LayoutControlItem22 = New DevExpress.XtraLayout.LayoutControlItem()
        Me.GroupControl1 = New DevExpress.XtraEditors.GroupControl()
        Me.LayoutControl5 = New DevExpress.XtraLayout.LayoutControl()
        Me.chkBoxShowScoreMaxOnSheet = New DevExpress.XtraEditors.CheckEdit()
        Me.useRedMark = New DevExpress.XtraEditors.CheckEdit()
        Me.showClassPostion = New DevExpress.XtraEditors.CheckEdit()
        Me.txt_redMark_percentage = New DevExpress.XtraEditors.TextEdit()
        Me.txt_textsscore_ = New DevExpress.XtraEditors.TextEdit()
        Me.txtexamScore = New DevExpress.XtraEditors.TextEdit()
        Me.txt_assScore = New DevExpress.XtraEditors.TextEdit()
        Me.LayoutControlGroup5 = New DevExpress.XtraLayout.LayoutControlGroup()
        Me.LayoutControlItem19 = New DevExpress.XtraLayout.LayoutControlItem()
        Me.LayoutControlItem20 = New DevExpress.XtraLayout.LayoutControlItem()
        Me.txt_testScore = New DevExpress.XtraLayout.LayoutControlItem()
        Me.LayoutControlItem28 = New DevExpress.XtraLayout.LayoutControlItem()
        Me.LayoutControlItem1 = New DevExpress.XtraLayout.LayoutControlItem()
        Me.LayoutControlItem21 = New DevExpress.XtraLayout.LayoutControlItem()
        Me.LayoutControlItem24 = New DevExpress.XtraLayout.LayoutControlItem()
        Me.LayoutControlGroup2 = New DevExpress.XtraLayout.LayoutControlGroup()
        Me.LayoutControlItem6 = New DevExpress.XtraLayout.LayoutControlItem()
        Me.LayoutControlItem15 = New DevExpress.XtraLayout.LayoutControlItem()
        Me.EmptySpaceItem12 = New DevExpress.XtraLayout.EmptySpaceItem()
        Me.EmptySpaceItem11 = New DevExpress.XtraLayout.EmptySpaceItem()
        Me.NavigationPage3 = New DevExpress.XtraBars.Navigation.NavigationPage()
        Me.WindowsUIButtonPanel1 = New DevExpress.XtraBars.Docking2010.WindowsUIButtonPanel()
        Me.EmptySpaceItem9 = New DevExpress.XtraLayout.EmptySpaceItem()
        Me.EmptySpaceItem10 = New DevExpress.XtraLayout.EmptySpaceItem()
        Me.NavigationPage4 = New DevExpress.XtraBars.Navigation.NavigationPage()
        CType(Me.NavigationFrame1, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.NavigationFrame1.SuspendLayout()
        Me.NavigationPage1.SuspendLayout()
        CType(Me.LayoutControl1, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.LayoutControl1.SuspendLayout()
        CType(Me.sch_name_tb.Properties, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.sch_address_tb.Properties, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.sch_motto_tb.Properties, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.sch_email_tb.Properties, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.sch_contact_no_tb.Properties, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.sch_logo_picedit.Properties, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.sch_website_tb.Properties, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.Sch_facebook_tb.Properties, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.sch_twitter_tb.Properties, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.sch_linkedIn_tb.Properties, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.LayoutControlGroup1, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.Root1, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.Root2, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.Root3, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.LayoutControlItem2, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.LayoutControlItem5, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.LayoutControlItem10, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.LayoutControlItem12, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.EmptySpaceItem4, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.LayoutControlItem13, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.EmptySpaceItem5, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.EmptySpaceItem19, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.EmptySpaceItem20, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.EmptySpaceItem21, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.LayoutControlItem4, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.LayoutControlItem3, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.Root4, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.Root5, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.Root6, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.LayoutControlItem7, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.LayoutControlItem9, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.LayoutControlItem11, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.LayoutControlItem14, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.EmptySpaceItem8, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.autoGeneratedGroup1, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.EmptySpaceItem2, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.autoGeneratedGroup0, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.EmptySpaceItem7, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.EmptySpaceItem1, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.EmptySpaceItem3, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.EmptySpaceItem6, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.NavigationPage2.SuspendLayout()
        CType(Me.LayoutControl2, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.LayoutControl2.SuspendLayout()
        CType(Me.GroupControl3, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.GroupControl3.SuspendLayout()
        CType(Me.LayoutControl4, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.LayoutControl4.SuspendLayout()
        CType(Me.idNoInitial.Properties, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.LayoutControlGroup4, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.LayoutControlItem22, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.GroupControl1, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.GroupControl1.SuspendLayout()
        CType(Me.LayoutControl5, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.LayoutControl5.SuspendLayout()
        CType(Me.chkBoxShowScoreMaxOnSheet.Properties, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.useRedMark.Properties, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.showClassPostion.Properties, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.txt_redMark_percentage.Properties, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.txt_textsscore_.Properties, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.txtexamScore.Properties, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.txt_assScore.Properties, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.LayoutControlGroup5, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.LayoutControlItem19, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.LayoutControlItem20, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.txt_testScore, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.LayoutControlItem28, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.LayoutControlItem1, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.LayoutControlItem21, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.LayoutControlItem24, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.LayoutControlGroup2, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.LayoutControlItem6, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.LayoutControlItem15, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.EmptySpaceItem12, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.EmptySpaceItem11, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.EmptySpaceItem9, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.EmptySpaceItem10, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.SuspendLayout()
        '
        'windowsUIButtonPanelMain
        '
        Me.windowsUIButtonPanelMain.AllowGlyphSkinning = False
        Me.windowsUIButtonPanelMain.AppearanceButton.Hovered.BackColor = System.Drawing.Color.FromArgb(CType(CType(130, Byte), Integer), CType(CType(130, Byte), Integer), CType(CType(130, Byte), Integer))
        Me.windowsUIButtonPanelMain.AppearanceButton.Hovered.FontSizeDelta = -1
        Me.windowsUIButtonPanelMain.AppearanceButton.Hovered.ForeColor = System.Drawing.Color.FromArgb(CType(CType(130, Byte), Integer), CType(CType(130, Byte), Integer), CType(CType(130, Byte), Integer))
        Me.windowsUIButtonPanelMain.AppearanceButton.Hovered.Options.UseBackColor = True
        Me.windowsUIButtonPanelMain.AppearanceButton.Hovered.Options.UseFont = True
        Me.windowsUIButtonPanelMain.AppearanceButton.Hovered.Options.UseForeColor = True
        Me.windowsUIButtonPanelMain.AppearanceButton.Normal.FontSizeDelta = -1
        Me.windowsUIButtonPanelMain.AppearanceButton.Normal.Options.UseFont = True
        Me.windowsUIButtonPanelMain.AppearanceButton.Pressed.BackColor = System.Drawing.Color.FromArgb(CType(CType(159, Byte), Integer), CType(CType(159, Byte), Integer), CType(CType(159, Byte), Integer))
        Me.windowsUIButtonPanelMain.AppearanceButton.Pressed.FontSizeDelta = -1
        Me.windowsUIButtonPanelMain.AppearanceButton.Pressed.ForeColor = System.Drawing.Color.FromArgb(CType(CType(159, Byte), Integer), CType(CType(159, Byte), Integer), CType(CType(159, Byte), Integer))
        Me.windowsUIButtonPanelMain.AppearanceButton.Pressed.Options.UseBackColor = True
        Me.windowsUIButtonPanelMain.AppearanceButton.Pressed.Options.UseFont = True
        Me.windowsUIButtonPanelMain.AppearanceButton.Pressed.Options.UseForeColor = True
        Me.windowsUIButtonPanelMain.BackColor = System.Drawing.Color.FromArgb(CType(CType(63, Byte), Integer), CType(CType(63, Byte), Integer), CType(CType(63, Byte), Integer))
        Me.windowsUIButtonPanelMain.ButtonInterval = 40
        WindowsUIButtonImageOptions6.Image = CType(resources.GetObject("WindowsUIButtonImageOptions6.Image"), System.Drawing.Image)
        WindowsUIButtonImageOptions6.ImageUri.Uri = "Save;GrayScaled"
        WindowsUIButtonImageOptions7.Image = CType(resources.GetObject("WindowsUIButtonImageOptions7.Image"), System.Drawing.Image)
        WindowsUIButtonImageOptions8.Image = CType(resources.GetObject("WindowsUIButtonImageOptions8.Image"), System.Drawing.Image)
        WindowsUIButtonImageOptions9.SvgImage = CType(resources.GetObject("WindowsUIButtonImageOptions9.SvgImage"), DevExpress.Utils.Svg.SvgImage)
        Me.windowsUIButtonPanelMain.Buttons.AddRange(New DevExpress.XtraEditors.ButtonPanel.IBaseButton() {New DevExpress.XtraBars.Docking2010.WindowsUIButton("School Info", True, WindowsUIButtonImageOptions6, DevExpress.XtraBars.Docking2010.ButtonStyle.PushButton, "School Info", 1, True, Nothing, True, False, True, Nothing, -1, False), New DevExpress.XtraBars.Docking2010.WindowsUIButton("Report Settings", True, WindowsUIButtonImageOptions7, DevExpress.XtraBars.Docking2010.ButtonStyle.PushButton, "", 2, True, Nothing, True, False, True, Nothing, -1, False), New DevExpress.XtraBars.Docking2010.WindowsUIButton("User Manager", True, WindowsUIButtonImageOptions8, DevExpress.XtraBars.Docking2010.ButtonStyle.PushButton, "", -1, True, Nothing, True, False, True, Nothing, -1, False), New DevExpress.XtraBars.Docking2010.WindowsUIButton("Session Settings", True, WindowsUIButtonImageOptions9, DevExpress.XtraBars.Docking2010.ButtonStyle.PushButton, "", -1, True, Nothing, True, False, True, Nothing, -1, False)})
        Me.windowsUIButtonPanelMain.Dock = System.Windows.Forms.DockStyle.Top
        Me.windowsUIButtonPanelMain.EnableImageTransparency = True
        Me.windowsUIButtonPanelMain.ForeColor = System.Drawing.Color.White
        Me.windowsUIButtonPanelMain.Location = New System.Drawing.Point(0, 0)
        Me.windowsUIButtonPanelMain.Margin = New System.Windows.Forms.Padding(4, 5, 4, 5)
        Me.windowsUIButtonPanelMain.MaximumSize = New System.Drawing.Size(0, 60)
        Me.windowsUIButtonPanelMain.MinimumSize = New System.Drawing.Size(60, 60)
        Me.windowsUIButtonPanelMain.Name = "windowsUIButtonPanelMain"
        Me.windowsUIButtonPanelMain.Size = New System.Drawing.Size(981, 60)
        Me.windowsUIButtonPanelMain.TabIndex = 15
        Me.windowsUIButtonPanelMain.Text = "windowsUIButtonPanelMain"
        Me.windowsUIButtonPanelMain.UseButtonBackgroundImages = False
        '
        'NavigationFrame1
        '
        Me.NavigationFrame1.Controls.Add(Me.NavigationPage1)
        Me.NavigationFrame1.Controls.Add(Me.NavigationPage2)
        Me.NavigationFrame1.Controls.Add(Me.NavigationPage3)
        Me.NavigationFrame1.Controls.Add(Me.NavigationPage4)
        Me.NavigationFrame1.Dock = System.Windows.Forms.DockStyle.Fill
        Me.NavigationFrame1.Location = New System.Drawing.Point(0, 60)
        Me.NavigationFrame1.Name = "NavigationFrame1"
        Me.NavigationFrame1.Pages.AddRange(New DevExpress.XtraBars.Navigation.NavigationPageBase() {Me.NavigationPage1, Me.NavigationPage2, Me.NavigationPage3, Me.NavigationPage4})
        Me.NavigationFrame1.SelectedPage = Me.NavigationPage2
        Me.NavigationFrame1.Size = New System.Drawing.Size(981, 517)
        Me.NavigationFrame1.TabIndex = 16
        Me.NavigationFrame1.Text = "NavigationFrame1"
        '
        'NavigationPage1
        '
        Me.NavigationPage1.Caption = "NavigationPage1"
        Me.NavigationPage1.Controls.Add(Me.LayoutControl1)
        Me.NavigationPage1.Name = "NavigationPage1"
        Me.NavigationPage1.Size = New System.Drawing.Size(981, 517)
        '
        'LayoutControl1
        '
        Me.LayoutControl1.Controls.Add(Me.sch_name_tb)
        Me.LayoutControl1.Controls.Add(Me.sch_address_tb)
        Me.LayoutControl1.Controls.Add(Me.sch_motto_tb)
        Me.LayoutControl1.Controls.Add(Me.sch_email_tb)
        Me.LayoutControl1.Controls.Add(Me.sch_contact_no_tb)
        Me.LayoutControl1.Controls.Add(Me.sch_logo_picedit)
        Me.LayoutControl1.Controls.Add(Me.SimpleButton1)
        Me.LayoutControl1.Controls.Add(Me.sch_website_tb)
        Me.LayoutControl1.Controls.Add(Me.Sch_facebook_tb)
        Me.LayoutControl1.Controls.Add(Me.sch_twitter_tb)
        Me.LayoutControl1.Controls.Add(Me.sch_linkedIn_tb)
        Me.LayoutControl1.Dock = System.Windows.Forms.DockStyle.Fill
        Me.LayoutControl1.Location = New System.Drawing.Point(0, 0)
        Me.LayoutControl1.Name = "LayoutControl1"
        Me.LayoutControl1.OptionsCustomizationForm.DesignTimeCustomizationFormPositionAndSize = New System.Drawing.Rectangle(308, 392, 650, 400)
        Me.LayoutControl1.Root = Me.LayoutControlGroup1
        Me.LayoutControl1.Size = New System.Drawing.Size(981, 517)
        Me.LayoutControl1.TabIndex = 0
        Me.LayoutControl1.Text = "LayoutControl1"
        '
        'sch_name_tb
        '
        Me.sch_name_tb.Location = New System.Drawing.Point(138, 61)
        Me.sch_name_tb.Name = "sch_name_tb"
        Me.sch_name_tb.Properties.Appearance.Font = New System.Drawing.Font("Tahoma", 9.75!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.sch_name_tb.Properties.Appearance.Options.UseFont = True
        Me.sch_name_tb.Properties.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.Flat
        Me.sch_name_tb.Properties.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper
        Me.sch_name_tb.Size = New System.Drawing.Size(257, 40)
        Me.sch_name_tb.StyleController = Me.LayoutControl1
        Me.sch_name_tb.TabIndex = 4
        '
        'sch_address_tb
        '
        Me.sch_address_tb.Location = New System.Drawing.Point(138, 328)
        Me.sch_address_tb.Name = "sch_address_tb"
        Me.sch_address_tb.Properties.Appearance.Font = New System.Drawing.Font("Tahoma", 9.75!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.sch_address_tb.Properties.Appearance.Options.UseFont = True
        Me.sch_address_tb.Properties.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.Flat
        Me.sch_address_tb.Size = New System.Drawing.Size(257, 89)
        Me.sch_address_tb.StyleController = Me.LayoutControl1
        Me.sch_address_tb.TabIndex = 5
        '
        'sch_motto_tb
        '
        Me.sch_motto_tb.Location = New System.Drawing.Point(138, 193)
        Me.sch_motto_tb.Name = "sch_motto_tb"
        Me.sch_motto_tb.Properties.Appearance.Font = New System.Drawing.Font("Tahoma", 9.75!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.sch_motto_tb.Properties.Appearance.Options.UseFont = True
        Me.sch_motto_tb.Properties.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.Flat
        Me.sch_motto_tb.Size = New System.Drawing.Size(257, 40)
        Me.sch_motto_tb.StyleController = Me.LayoutControl1
        Me.sch_motto_tb.TabIndex = 6
        '
        'sch_email_tb
        '
        Me.sch_email_tb.Location = New System.Drawing.Point(138, 126)
        Me.sch_email_tb.Name = "sch_email_tb"
        Me.sch_email_tb.Properties.Appearance.Font = New System.Drawing.Font("Tahoma", 9.75!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.sch_email_tb.Properties.Appearance.Options.UseFont = True
        Me.sch_email_tb.Properties.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.Flat
        Me.sch_email_tb.Properties.Mask.EditMask = "[a-zA-Z]+"
        Me.sch_email_tb.Size = New System.Drawing.Size(257, 40)
        Me.sch_email_tb.StyleController = Me.LayoutControl1
        Me.sch_email_tb.TabIndex = 7
        '
        'sch_contact_no_tb
        '
        Me.sch_contact_no_tb.Location = New System.Drawing.Point(138, 260)
        Me.sch_contact_no_tb.Name = "sch_contact_no_tb"
        Me.sch_contact_no_tb.Properties.Appearance.Font = New System.Drawing.Font("Tahoma", 9.75!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.sch_contact_no_tb.Properties.Appearance.Options.UseFont = True
        Me.sch_contact_no_tb.Properties.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.Flat
        Me.sch_contact_no_tb.Properties.Mask.EditMask = "d"
        Me.sch_contact_no_tb.Size = New System.Drawing.Size(257, 40)
        Me.sch_contact_no_tb.StyleController = Me.LayoutControl1
        Me.sch_contact_no_tb.TabIndex = 8
        '
        'sch_logo_picedit
        '
        Me.sch_logo_picedit.Cursor = System.Windows.Forms.Cursors.Default
        Me.sch_logo_picedit.Location = New System.Drawing.Point(682, 61)
        Me.sch_logo_picedit.Name = "sch_logo_picedit"
        Me.sch_logo_picedit.Properties.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.NoBorder
        Me.sch_logo_picedit.Properties.InitialImageOptions.Image = CType(resources.GetObject("sch_logo_picedit.Properties.InitialImageOptions.Image"), System.Drawing.Image)
        Me.sch_logo_picedit.Properties.ShowCameraMenuItem = DevExpress.XtraEditors.Controls.CameraMenuItemVisibility.[Auto]
        Me.sch_logo_picedit.Properties.SizeMode = DevExpress.XtraEditors.Controls.PictureSizeMode.Stretch
        Me.sch_logo_picedit.Size = New System.Drawing.Size(180, 147)
        Me.sch_logo_picedit.StyleController = Me.LayoutControl1
        Me.sch_logo_picedit.TabIndex = 9
        Me.sch_logo_picedit.ToolTip = "Enter School Logo"
        '
        'SimpleButton1
        '
        Me.SimpleButton1.Location = New System.Drawing.Point(682, 230)
        Me.SimpleButton1.Name = "SimpleButton1"
        Me.SimpleButton1.Size = New System.Drawing.Size(180, 42)
        Me.SimpleButton1.StyleController = Me.LayoutControl1
        Me.SimpleButton1.TabIndex = 10
        Me.SimpleButton1.Text = "Select School logo"
        '
        'sch_website_tb
        '
        Me.sch_website_tb.Location = New System.Drawing.Point(410, 61)
        Me.sch_website_tb.Name = "sch_website_tb"
        Me.sch_website_tb.Properties.Appearance.Font = New System.Drawing.Font("Tahoma", 9.75!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.sch_website_tb.Properties.Appearance.Options.UseFont = True
        Me.sch_website_tb.Properties.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.Flat
        Me.sch_website_tb.Size = New System.Drawing.Size(258, 40)
        Me.sch_website_tb.StyleController = Me.LayoutControl1
        Me.sch_website_tb.TabIndex = 4
        '
        'Sch_facebook_tb
        '
        Me.Sch_facebook_tb.Location = New System.Drawing.Point(410, 124)
        Me.Sch_facebook_tb.Name = "Sch_facebook_tb"
        Me.Sch_facebook_tb.Properties.Appearance.Font = New System.Drawing.Font("Tahoma", 9.75!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.Sch_facebook_tb.Properties.Appearance.Options.UseFont = True
        Me.Sch_facebook_tb.Properties.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.Flat
        Me.Sch_facebook_tb.Size = New System.Drawing.Size(258, 40)
        Me.Sch_facebook_tb.StyleController = Me.LayoutControl1
        Me.Sch_facebook_tb.TabIndex = 6
        '
        'sch_twitter_tb
        '
        Me.sch_twitter_tb.Location = New System.Drawing.Point(410, 194)
        Me.sch_twitter_tb.Name = "sch_twitter_tb"
        Me.sch_twitter_tb.Properties.Appearance.Font = New System.Drawing.Font("Tahoma", 9.75!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.sch_twitter_tb.Properties.Appearance.Options.UseFont = True
        Me.sch_twitter_tb.Properties.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.Flat
        Me.sch_twitter_tb.Properties.Mask.EditMask = "[a-zA-Z]+"
        Me.sch_twitter_tb.Size = New System.Drawing.Size(258, 40)
        Me.sch_twitter_tb.StyleController = Me.LayoutControl1
        Me.sch_twitter_tb.TabIndex = 7
        '
        'sch_linkedIn_tb
        '
        Me.sch_linkedIn_tb.Location = New System.Drawing.Point(410, 260)
        Me.sch_linkedIn_tb.Name = "sch_linkedIn_tb"
        Me.sch_linkedIn_tb.Properties.Appearance.Font = New System.Drawing.Font("Tahoma", 9.75!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.sch_linkedIn_tb.Properties.Appearance.Options.UseFont = True
        Me.sch_linkedIn_tb.Properties.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.Flat
        Me.sch_linkedIn_tb.Properties.Mask.EditMask = "d"
        Me.sch_linkedIn_tb.Size = New System.Drawing.Size(258, 40)
        Me.sch_linkedIn_tb.StyleController = Me.LayoutControl1
        Me.sch_linkedIn_tb.TabIndex = 8
        '
        'LayoutControlGroup1
        '
        Me.LayoutControlGroup1.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.[True]
        Me.LayoutControlGroup1.GroupBordersVisible = False
        Me.LayoutControlGroup1.Items.AddRange(New DevExpress.XtraLayout.BaseLayoutItem() {Me.Root1})
        Me.LayoutControlGroup1.Name = "Root"
        Me.LayoutControlGroup1.Size = New System.Drawing.Size(981, 517)
        Me.LayoutControlGroup1.TextVisible = False
        '
        'Root1
        '
        Me.Root1.CustomizationFormText = "Root"
        Me.Root1.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.[True]
        Me.Root1.GroupBordersVisible = False
        Me.Root1.Items.AddRange(New DevExpress.XtraLayout.BaseLayoutItem() {Me.Root2, Me.EmptySpaceItem1, Me.EmptySpaceItem3, Me.EmptySpaceItem6})
        Me.Root1.Location = New System.Drawing.Point(0, 0)
        Me.Root1.Name = "Root1"
        Me.Root1.Size = New System.Drawing.Size(961, 497)
        Me.Root1.Spacing = New DevExpress.XtraLayout.Utils.Padding(0, 0, 0, 0)
        Me.Root1.Text = "Root"
        Me.Root1.TextVisible = False
        '
        'Root2
        '
        Me.Root2.CustomizationFormText = "Root"
        Me.Root2.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.[True]
        Me.Root2.GroupBordersVisible = False
        Me.Root2.Items.AddRange(New DevExpress.XtraLayout.BaseLayoutItem() {Me.Root3, Me.autoGeneratedGroup0, Me.EmptySpaceItem7})
        Me.Root2.Location = New System.Drawing.Point(96, 0)
        Me.Root2.Name = "Root2"
        Me.Root2.Size = New System.Drawing.Size(845, 431)
        Me.Root2.Spacing = New DevExpress.XtraLayout.Utils.Padding(0, 0, 0, 0)
        Me.Root2.Text = "Root"
        Me.Root2.TextVisible = False
        '
        'Root3
        '
        Me.Root3.CustomizationFormText = "Root"
        Me.Root3.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.[True]
        Me.Root3.GroupBordersVisible = False
        Me.Root3.Items.AddRange(New DevExpress.XtraLayout.BaseLayoutItem() {Me.LayoutControlItem2, Me.LayoutControlItem5, Me.LayoutControlItem10, Me.LayoutControlItem12, Me.EmptySpaceItem4, Me.LayoutControlItem13, Me.EmptySpaceItem5, Me.EmptySpaceItem19, Me.EmptySpaceItem20, Me.EmptySpaceItem21, Me.LayoutControlItem4, Me.LayoutControlItem3, Me.Root4, Me.EmptySpaceItem2})
        Me.Root3.Location = New System.Drawing.Point(0, 0)
        Me.Root3.Name = "Root3"
        Me.Root3.Size = New System.Drawing.Size(748, 409)
        Me.Root3.Spacing = New DevExpress.XtraLayout.Utils.Padding(0, 0, 0, 0)
        Me.Root3.Text = "Root"
        Me.Root3.TextVisible = False
        '
        'LayoutControlItem2
        '
        Me.LayoutControlItem2.AppearanceItemCaption.Font = New System.Drawing.Font("Tahoma", 10.0!)
        Me.LayoutControlItem2.AppearanceItemCaption.Options.UseFont = True
        Me.LayoutControlItem2.Control = Me.sch_name_tb
        Me.LayoutControlItem2.CustomizationFormText = "Address line 1:"
        Me.LayoutControlItem2.Location = New System.Drawing.Point(0, 0)
        Me.LayoutControlItem2.MaxSize = New System.Drawing.Size(404, 0)
        Me.LayoutControlItem2.MinSize = New System.Drawing.Size(116, 40)
        Me.LayoutControlItem2.Name = "LayoutControlItem2"
        Me.LayoutControlItem2.Size = New System.Drawing.Size(261, 65)
        Me.LayoutControlItem2.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom
        Me.LayoutControlItem2.Text = "Enter School Name"
        Me.LayoutControlItem2.TextLocation = DevExpress.Utils.Locations.Top
        Me.LayoutControlItem2.TextSize = New System.Drawing.Size(109, 16)
        '
        'LayoutControlItem5
        '
        Me.LayoutControlItem5.AppearanceItemCaption.Font = New System.Drawing.Font("Tahoma", 10.0!)
        Me.LayoutControlItem5.AppearanceItemCaption.Options.UseFont = True
        Me.LayoutControlItem5.Control = Me.sch_email_tb
        Me.LayoutControlItem5.CustomizationFormText = "State/Province/Region:"
        Me.LayoutControlItem5.Location = New System.Drawing.Point(0, 65)
        Me.LayoutControlItem5.MaxSize = New System.Drawing.Size(404, 0)
        Me.LayoutControlItem5.MinSize = New System.Drawing.Size(116, 40)
        Me.LayoutControlItem5.Name = "LayoutControlItem5"
        Me.LayoutControlItem5.Size = New System.Drawing.Size(261, 67)
        Me.LayoutControlItem5.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom
        Me.LayoutControlItem5.Text = "School Email"
        Me.LayoutControlItem5.TextLocation = DevExpress.Utils.Locations.Top
        Me.LayoutControlItem5.TextSize = New System.Drawing.Size(109, 16)
        '
        'LayoutControlItem10
        '
        Me.LayoutControlItem10.AppearanceItemCaption.Font = New System.Drawing.Font("Tahoma", 10.0!)
        Me.LayoutControlItem10.AppearanceItemCaption.Options.UseFont = True
        Me.LayoutControlItem10.Control = Me.sch_contact_no_tb
        Me.LayoutControlItem10.CustomizationFormText = "ZIP:"
        Me.LayoutControlItem10.Location = New System.Drawing.Point(0, 199)
        Me.LayoutControlItem10.MaxSize = New System.Drawing.Size(404, 0)
        Me.LayoutControlItem10.MinSize = New System.Drawing.Size(116, 40)
        Me.LayoutControlItem10.Name = "LayoutControlItem10"
        Me.LayoutControlItem10.Size = New System.Drawing.Size(261, 68)
        Me.LayoutControlItem10.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom
        Me.LayoutControlItem10.Text = "School Contact No."
        Me.LayoutControlItem10.TextLocation = DevExpress.Utils.Locations.Top
        Me.LayoutControlItem10.TextSize = New System.Drawing.Size(109, 16)
        '
        'LayoutControlItem12
        '
        Me.LayoutControlItem12.Control = Me.sch_logo_picedit
        Me.LayoutControlItem12.CustomizationFormText = "LayoutControlItem6"
        Me.LayoutControlItem12.Location = New System.Drawing.Point(544, 19)
        Me.LayoutControlItem12.Name = "LayoutControlItem12"
        Me.LayoutControlItem12.Size = New System.Drawing.Size(184, 151)
        Me.LayoutControlItem12.Text = "LayoutControlItem6"
        Me.LayoutControlItem12.TextSize = New System.Drawing.Size(0, 0)
        Me.LayoutControlItem12.TextVisible = False
        '
        'EmptySpaceItem4
        '
        Me.EmptySpaceItem4.AllowHotTrack = False
        Me.EmptySpaceItem4.CustomizationFormText = "EmptySpaceItem1"
        Me.EmptySpaceItem4.Location = New System.Drawing.Point(261, 0)
        Me.EmptySpaceItem4.Name = "EmptySpaceItem4"
        Me.EmptySpaceItem4.Size = New System.Drawing.Size(11, 389)
        Me.EmptySpaceItem4.Text = "EmptySpaceItem1"
        Me.EmptySpaceItem4.TextSize = New System.Drawing.Size(0, 0)
        '
        'LayoutControlItem13
        '
        Me.LayoutControlItem13.Control = Me.SimpleButton1
        Me.LayoutControlItem13.CustomizationFormText = "LayoutControlItem7"
        Me.LayoutControlItem13.Location = New System.Drawing.Point(544, 188)
        Me.LayoutControlItem13.Name = "LayoutControlItem13"
        Me.LayoutControlItem13.Size = New System.Drawing.Size(184, 46)
        Me.LayoutControlItem13.Text = "LayoutControlItem7"
        Me.LayoutControlItem13.TextSize = New System.Drawing.Size(0, 0)
        Me.LayoutControlItem13.TextVisible = False
        '
        'EmptySpaceItem5
        '
        Me.EmptySpaceItem5.AllowHotTrack = False
        Me.EmptySpaceItem5.CustomizationFormText = "EmptySpaceItem2"
        Me.EmptySpaceItem5.Location = New System.Drawing.Point(0, 379)
        Me.EmptySpaceItem5.Name = "EmptySpaceItem5"
        Me.EmptySpaceItem5.Size = New System.Drawing.Size(261, 10)
        Me.EmptySpaceItem5.Text = "EmptySpaceItem2"
        Me.EmptySpaceItem5.TextSize = New System.Drawing.Size(0, 0)
        '
        'EmptySpaceItem19
        '
        Me.EmptySpaceItem19.AllowHotTrack = False
        Me.EmptySpaceItem19.CustomizationFormText = "EmptySpaceItem3"
        Me.EmptySpaceItem19.Location = New System.Drawing.Point(544, 170)
        Me.EmptySpaceItem19.Name = "EmptySpaceItem19"
        Me.EmptySpaceItem19.Size = New System.Drawing.Size(184, 18)
        Me.EmptySpaceItem19.Text = "EmptySpaceItem3"
        Me.EmptySpaceItem19.TextSize = New System.Drawing.Size(0, 0)
        '
        'EmptySpaceItem20
        '
        Me.EmptySpaceItem20.AllowHotTrack = False
        Me.EmptySpaceItem20.CustomizationFormText = "EmptySpaceItem4"
        Me.EmptySpaceItem20.Location = New System.Drawing.Point(544, 0)
        Me.EmptySpaceItem20.Name = "EmptySpaceItem20"
        Me.EmptySpaceItem20.Size = New System.Drawing.Size(184, 19)
        Me.EmptySpaceItem20.Text = "EmptySpaceItem4"
        Me.EmptySpaceItem20.TextSize = New System.Drawing.Size(0, 0)
        '
        'EmptySpaceItem21
        '
        Me.EmptySpaceItem21.AllowHotTrack = False
        Me.EmptySpaceItem21.CustomizationFormText = "EmptySpaceItem5"
        Me.EmptySpaceItem21.Location = New System.Drawing.Point(544, 234)
        Me.EmptySpaceItem21.Name = "EmptySpaceItem21"
        Me.EmptySpaceItem21.Size = New System.Drawing.Size(184, 155)
        Me.EmptySpaceItem21.Text = "EmptySpaceItem5"
        Me.EmptySpaceItem21.TextSize = New System.Drawing.Size(0, 0)
        '
        'LayoutControlItem4
        '
        Me.LayoutControlItem4.AppearanceItemCaption.Font = New System.Drawing.Font("Tahoma", 10.0!)
        Me.LayoutControlItem4.AppearanceItemCaption.Options.UseFont = True
        Me.LayoutControlItem4.Control = Me.sch_motto_tb
        Me.LayoutControlItem4.CustomizationFormText = "City:"
        Me.LayoutControlItem4.Location = New System.Drawing.Point(0, 132)
        Me.LayoutControlItem4.MaxSize = New System.Drawing.Size(404, 0)
        Me.LayoutControlItem4.MinSize = New System.Drawing.Size(116, 40)
        Me.LayoutControlItem4.Name = "LayoutControlItem4"
        Me.LayoutControlItem4.Size = New System.Drawing.Size(261, 67)
        Me.LayoutControlItem4.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom
        Me.LayoutControlItem4.Text = "School Motto"
        Me.LayoutControlItem4.TextLocation = DevExpress.Utils.Locations.Top
        Me.LayoutControlItem4.TextSize = New System.Drawing.Size(109, 16)
        '
        'LayoutControlItem3
        '
        Me.LayoutControlItem3.AppearanceItemCaption.Font = New System.Drawing.Font("Tahoma", 10.0!)
        Me.LayoutControlItem3.AppearanceItemCaption.Options.UseFont = True
        Me.LayoutControlItem3.Control = Me.sch_address_tb
        Me.LayoutControlItem3.CustomizationFormText = "Address line 2:"
        Me.LayoutControlItem3.Location = New System.Drawing.Point(0, 267)
        Me.LayoutControlItem3.MinSize = New System.Drawing.Size(50, 25)
        Me.LayoutControlItem3.Name = "LayoutControlItem3"
        Me.LayoutControlItem3.Size = New System.Drawing.Size(261, 112)
        Me.LayoutControlItem3.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom
        Me.LayoutControlItem3.Text = "School Address"
        Me.LayoutControlItem3.TextLocation = DevExpress.Utils.Locations.Top
        Me.LayoutControlItem3.TextSize = New System.Drawing.Size(109, 16)
        '
        'Root4
        '
        Me.Root4.CustomizationFormText = "Root"
        Me.Root4.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.[True]
        Me.Root4.GroupBordersVisible = False
        Me.Root4.Items.AddRange(New DevExpress.XtraLayout.BaseLayoutItem() {Me.Root5})
        Me.Root4.Location = New System.Drawing.Point(272, 0)
        Me.Root4.Name = "Root4"
        Me.Root4.Padding = New DevExpress.XtraLayout.Utils.Padding(0, 0, 0, 0)
        Me.Root4.Size = New System.Drawing.Size(262, 389)
        Me.Root4.Spacing = New DevExpress.XtraLayout.Utils.Padding(0, 0, 0, 0)
        Me.Root4.Text = "Root"
        Me.Root4.TextVisible = False
        '
        'Root5
        '
        Me.Root5.CustomizationFormText = "Root"
        Me.Root5.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.[True]
        Me.Root5.GroupBordersVisible = False
        Me.Root5.Items.AddRange(New DevExpress.XtraLayout.BaseLayoutItem() {Me.Root6, Me.autoGeneratedGroup1})
        Me.Root5.Location = New System.Drawing.Point(0, 0)
        Me.Root5.Name = "Root5"
        Me.Root5.Padding = New DevExpress.XtraLayout.Utils.Padding(0, 0, 0, 0)
        Me.Root5.Size = New System.Drawing.Size(262, 389)
        Me.Root5.Spacing = New DevExpress.XtraLayout.Utils.Padding(0, 0, 0, 0)
        Me.Root5.Text = "Root"
        Me.Root5.TextVisible = False
        '
        'Root6
        '
        Me.Root6.CustomizationFormText = "Root"
        Me.Root6.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.[True]
        Me.Root6.GroupBordersVisible = False
        Me.Root6.Items.AddRange(New DevExpress.XtraLayout.BaseLayoutItem() {Me.LayoutControlItem7, Me.LayoutControlItem9, Me.LayoutControlItem11, Me.LayoutControlItem14, Me.EmptySpaceItem8})
        Me.Root6.Location = New System.Drawing.Point(0, 0)
        Me.Root6.Name = "Root6"
        Me.Root6.Padding = New DevExpress.XtraLayout.Utils.Padding(0, 0, 0, 0)
        Me.Root6.Size = New System.Drawing.Size(262, 388)
        Me.Root6.Spacing = New DevExpress.XtraLayout.Utils.Padding(0, 0, 0, 0)
        Me.Root6.Text = "Root"
        Me.Root6.TextVisible = False
        '
        'LayoutControlItem7
        '
        Me.LayoutControlItem7.AppearanceItemCaption.Font = New System.Drawing.Font("Tahoma", 10.0!)
        Me.LayoutControlItem7.AppearanceItemCaption.Options.UseFont = True
        Me.LayoutControlItem7.Control = Me.sch_website_tb
        Me.LayoutControlItem7.CustomizationFormText = "Address line 1:"
        Me.LayoutControlItem7.Location = New System.Drawing.Point(0, 0)
        Me.LayoutControlItem7.MaxSize = New System.Drawing.Size(404, 0)
        Me.LayoutControlItem7.MinSize = New System.Drawing.Size(116, 40)
        Me.LayoutControlItem7.Name = "LayoutControlItem7"
        Me.LayoutControlItem7.Size = New System.Drawing.Size(262, 63)
        Me.LayoutControlItem7.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom
        Me.LayoutControlItem7.Text = "School Website"
        Me.LayoutControlItem7.TextLocation = DevExpress.Utils.Locations.Top
        Me.LayoutControlItem7.TextSize = New System.Drawing.Size(109, 16)
        '
        'LayoutControlItem9
        '
        Me.LayoutControlItem9.AppearanceItemCaption.Font = New System.Drawing.Font("Tahoma", 10.0!)
        Me.LayoutControlItem9.AppearanceItemCaption.Options.UseFont = True
        Me.LayoutControlItem9.Control = Me.Sch_facebook_tb
        Me.LayoutControlItem9.CustomizationFormText = "City:"
        Me.LayoutControlItem9.Location = New System.Drawing.Point(0, 63)
        Me.LayoutControlItem9.MaxSize = New System.Drawing.Size(404, 0)
        Me.LayoutControlItem9.MinSize = New System.Drawing.Size(116, 40)
        Me.LayoutControlItem9.Name = "LayoutControlItem9"
        Me.LayoutControlItem9.Size = New System.Drawing.Size(262, 70)
        Me.LayoutControlItem9.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom
        Me.LayoutControlItem9.Text = "Facebook Handle"
        Me.LayoutControlItem9.TextLocation = DevExpress.Utils.Locations.Top
        Me.LayoutControlItem9.TextSize = New System.Drawing.Size(109, 16)
        '
        'LayoutControlItem11
        '
        Me.LayoutControlItem11.AppearanceItemCaption.Font = New System.Drawing.Font("Tahoma", 10.0!)
        Me.LayoutControlItem11.AppearanceItemCaption.Options.UseFont = True
        Me.LayoutControlItem11.Control = Me.sch_twitter_tb
        Me.LayoutControlItem11.CustomizationFormText = "State/Province/Region:"
        Me.LayoutControlItem11.Location = New System.Drawing.Point(0, 133)
        Me.LayoutControlItem11.MaxSize = New System.Drawing.Size(404, 0)
        Me.LayoutControlItem11.MinSize = New System.Drawing.Size(116, 40)
        Me.LayoutControlItem11.Name = "LayoutControlItem11"
        Me.LayoutControlItem11.Size = New System.Drawing.Size(262, 66)
        Me.LayoutControlItem11.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom
        Me.LayoutControlItem11.Text = "Twitter Handle"
        Me.LayoutControlItem11.TextLocation = DevExpress.Utils.Locations.Top
        Me.LayoutControlItem11.TextSize = New System.Drawing.Size(109, 16)
        '
        'LayoutControlItem14
        '
        Me.LayoutControlItem14.AppearanceItemCaption.Font = New System.Drawing.Font("Tahoma", 10.0!)
        Me.LayoutControlItem14.AppearanceItemCaption.Options.UseFont = True
        Me.LayoutControlItem14.Control = Me.sch_linkedIn_tb
        Me.LayoutControlItem14.CustomizationFormText = "ZIP:"
        Me.LayoutControlItem14.Location = New System.Drawing.Point(0, 199)
        Me.LayoutControlItem14.MaxSize = New System.Drawing.Size(404, 0)
        Me.LayoutControlItem14.MinSize = New System.Drawing.Size(116, 40)
        Me.LayoutControlItem14.Name = "LayoutControlItem14"
        Me.LayoutControlItem14.Size = New System.Drawing.Size(262, 175)
        Me.LayoutControlItem14.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom
        Me.LayoutControlItem14.Text = "LinkedIn "
        Me.LayoutControlItem14.TextLocation = DevExpress.Utils.Locations.Top
        Me.LayoutControlItem14.TextSize = New System.Drawing.Size(109, 16)
        '
        'EmptySpaceItem8
        '
        Me.EmptySpaceItem8.AllowHotTrack = False
        Me.EmptySpaceItem8.CustomizationFormText = "EmptySpaceItem2"
        Me.EmptySpaceItem8.Location = New System.Drawing.Point(0, 374)
        Me.EmptySpaceItem8.Name = "EmptySpaceItem8"
        Me.EmptySpaceItem8.Size = New System.Drawing.Size(262, 14)
        Me.EmptySpaceItem8.Text = "EmptySpaceItem2"
        Me.EmptySpaceItem8.TextSize = New System.Drawing.Size(0, 0)
        '
        'autoGeneratedGroup1
        '
        Me.autoGeneratedGroup1.AllowDrawBackground = False
        Me.autoGeneratedGroup1.CustomizationFormText = "autoGeneratedGroup0"
        Me.autoGeneratedGroup1.GroupBordersVisible = False
        Me.autoGeneratedGroup1.Location = New System.Drawing.Point(0, 388)
        Me.autoGeneratedGroup1.Name = "autoGeneratedGroup1"
        Me.autoGeneratedGroup1.Size = New System.Drawing.Size(262, 1)
        Me.autoGeneratedGroup1.Text = "autoGeneratedGroup0"
        '
        'EmptySpaceItem2
        '
        Me.EmptySpaceItem2.AllowHotTrack = False
        Me.EmptySpaceItem2.Location = New System.Drawing.Point(534, 0)
        Me.EmptySpaceItem2.Name = "EmptySpaceItem2"
        Me.EmptySpaceItem2.Size = New System.Drawing.Size(10, 389)
        Me.EmptySpaceItem2.TextSize = New System.Drawing.Size(0, 0)
        '
        'autoGeneratedGroup0
        '
        Me.autoGeneratedGroup0.AllowDrawBackground = False
        Me.autoGeneratedGroup0.CustomizationFormText = "autoGeneratedGroup0"
        Me.autoGeneratedGroup0.GroupBordersVisible = False
        Me.autoGeneratedGroup0.Location = New System.Drawing.Point(0, 409)
        Me.autoGeneratedGroup0.Name = "autoGeneratedGroup0"
        Me.autoGeneratedGroup0.Size = New System.Drawing.Size(825, 2)
        '
        'EmptySpaceItem7
        '
        Me.EmptySpaceItem7.AllowHotTrack = False
        Me.EmptySpaceItem7.Location = New System.Drawing.Point(748, 0)
        Me.EmptySpaceItem7.Name = "EmptySpaceItem7"
        Me.EmptySpaceItem7.Size = New System.Drawing.Size(77, 409)
        Me.EmptySpaceItem7.TextSize = New System.Drawing.Size(0, 0)
        '
        'EmptySpaceItem1
        '
        Me.EmptySpaceItem1.AllowHotTrack = False
        Me.EmptySpaceItem1.Location = New System.Drawing.Point(0, 0)
        Me.EmptySpaceItem1.Name = "EmptySpaceItem1"
        Me.EmptySpaceItem1.Size = New System.Drawing.Size(96, 477)
        Me.EmptySpaceItem1.TextSize = New System.Drawing.Size(0, 0)
        '
        'EmptySpaceItem3
        '
        Me.EmptySpaceItem3.AllowHotTrack = False
        Me.EmptySpaceItem3.Location = New System.Drawing.Point(96, 431)
        Me.EmptySpaceItem3.Name = "EmptySpaceItem3"
        Me.EmptySpaceItem3.Size = New System.Drawing.Size(560, 46)
        Me.EmptySpaceItem3.TextSize = New System.Drawing.Size(0, 0)
        '
        'EmptySpaceItem6
        '
        Me.EmptySpaceItem6.AllowHotTrack = False
        Me.EmptySpaceItem6.Location = New System.Drawing.Point(656, 431)
        Me.EmptySpaceItem6.Name = "EmptySpaceItem6"
        Me.EmptySpaceItem6.Size = New System.Drawing.Size(285, 46)
        Me.EmptySpaceItem6.TextSize = New System.Drawing.Size(0, 0)
        '
        'NavigationPage2
        '
        Me.NavigationPage2.Caption = "NavigationPage2"
        Me.NavigationPage2.Controls.Add(Me.LayoutControl2)
        Me.NavigationPage2.Name = "NavigationPage2"
        Me.NavigationPage2.Size = New System.Drawing.Size(981, 517)
        '
        'LayoutControl2
        '
        Me.LayoutControl2.Controls.Add(Me.GroupControl3)
        Me.LayoutControl2.Controls.Add(Me.GroupControl1)
        Me.LayoutControl2.Dock = System.Windows.Forms.DockStyle.Fill
        Me.LayoutControl2.Location = New System.Drawing.Point(0, 0)
        Me.LayoutControl2.Name = "LayoutControl2"
        Me.LayoutControl2.OptionsCustomizationForm.DesignTimeCustomizationFormPositionAndSize = New System.Drawing.Rectangle(1751, 246, 650, 400)
        Me.LayoutControl2.Root = Me.LayoutControlGroup2
        Me.LayoutControl2.Size = New System.Drawing.Size(981, 517)
        Me.LayoutControl2.TabIndex = 0
        Me.LayoutControl2.Text = "LayoutControl2"
        '
        'GroupControl3
        '
        Me.GroupControl3.Controls.Add(Me.LayoutControl4)
        Me.GroupControl3.Location = New System.Drawing.Point(104, 12)
        Me.GroupControl3.Name = "GroupControl3"
        Me.GroupControl3.ShowCaption = False
        Me.GroupControl3.Size = New System.Drawing.Size(619, 70)
        Me.GroupControl3.TabIndex = 5
        Me.GroupControl3.Text = "Number of days school opened"
        '
        'LayoutControl4
        '
        Me.LayoutControl4.Controls.Add(Me.idNoInitial)
        Me.LayoutControl4.Dock = System.Windows.Forms.DockStyle.Fill
        Me.LayoutControl4.Location = New System.Drawing.Point(2, 2)
        Me.LayoutControl4.Name = "LayoutControl4"
        Me.LayoutControl4.OptionsCustomizationForm.DesignTimeCustomizationFormPositionAndSize = New System.Drawing.Rectangle(2034, 111, 650, 400)
        Me.LayoutControl4.Root = Me.LayoutControlGroup4
        Me.LayoutControl4.Size = New System.Drawing.Size(615, 66)
        Me.LayoutControl4.TabIndex = 0
        Me.LayoutControl4.Text = "LayoutControl4"
        '
        'idNoInitial
        '
        Me.idNoInitial.Location = New System.Drawing.Point(142, 12)
        Me.idNoInitial.Name = "idNoInitial"
        Me.idNoInitial.Size = New System.Drawing.Size(461, 36)
        Me.idNoInitial.StyleController = Me.LayoutControl4
        Me.idNoInitial.TabIndex = 6
        '
        'LayoutControlGroup4
        '
        Me.LayoutControlGroup4.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.[True]
        Me.LayoutControlGroup4.GroupBordersVisible = False
        Me.LayoutControlGroup4.Items.AddRange(New DevExpress.XtraLayout.BaseLayoutItem() {Me.LayoutControlItem22})
        Me.LayoutControlGroup4.Name = "Root"
        Me.LayoutControlGroup4.Size = New System.Drawing.Size(615, 66)
        Me.LayoutControlGroup4.TextVisible = False
        '
        'LayoutControlItem22
        '
        Me.LayoutControlItem22.Control = Me.idNoInitial
        Me.LayoutControlItem22.Location = New System.Drawing.Point(0, 0)
        Me.LayoutControlItem22.Name = "LayoutControlItem22"
        Me.LayoutControlItem22.Size = New System.Drawing.Size(595, 46)
        Me.LayoutControlItem22.Text = "Admission Number initial:"
        Me.LayoutControlItem22.TextSize = New System.Drawing.Size(118, 13)
        '
        'GroupControl1
        '
        Me.GroupControl1.Controls.Add(Me.LayoutControl5)
        Me.GroupControl1.Location = New System.Drawing.Point(104, 86)
        Me.GroupControl1.Name = "GroupControl1"
        Me.GroupControl1.Size = New System.Drawing.Size(619, 419)
        Me.GroupControl1.TabIndex = 4
        Me.GroupControl1.Text = "Report settings - set max scores."
        '
        'LayoutControl5
        '
        Me.LayoutControl5.Controls.Add(Me.chkBoxShowScoreMaxOnSheet)
        Me.LayoutControl5.Controls.Add(Me.useRedMark)
        Me.LayoutControl5.Controls.Add(Me.showClassPostion)
        Me.LayoutControl5.Controls.Add(Me.txt_redMark_percentage)
        Me.LayoutControl5.Controls.Add(Me.txt_textsscore_)
        Me.LayoutControl5.Controls.Add(Me.txtexamScore)
        Me.LayoutControl5.Controls.Add(Me.txt_assScore)
        Me.LayoutControl5.Dock = System.Windows.Forms.DockStyle.Fill
        Me.LayoutControl5.Location = New System.Drawing.Point(2, 23)
        Me.LayoutControl5.Name = "LayoutControl5"
        Me.LayoutControl5.OptionsCustomizationForm.DesignTimeCustomizationFormPositionAndSize = New System.Drawing.Rectangle(72, 519, 650, 207)
        Me.LayoutControl5.Root = Me.LayoutControlGroup5
        Me.LayoutControl5.Size = New System.Drawing.Size(615, 394)
        Me.LayoutControl5.TabIndex = 0
        Me.LayoutControl5.Text = "LayoutControl5"
        '
        'chkBoxShowScoreMaxOnSheet
        '
        Me.chkBoxShowScoreMaxOnSheet.Location = New System.Drawing.Point(147, 228)
        Me.chkBoxShowScoreMaxOnSheet.Name = "chkBoxShowScoreMaxOnSheet"
        Me.chkBoxShowScoreMaxOnSheet.Properties.Caption = "Show Score Max on Sheet"
        Me.chkBoxShowScoreMaxOnSheet.Size = New System.Drawing.Size(303, 20)
        Me.chkBoxShowScoreMaxOnSheet.StyleController = Me.LayoutControl5
        Me.chkBoxShowScoreMaxOnSheet.TabIndex = 13
        '
        'useRedMark
        '
        Me.useRedMark.EditValue = True
        Me.useRedMark.Location = New System.Drawing.Point(147, 180)
        Me.useRedMark.Name = "useRedMark"
        Me.useRedMark.Properties.Caption = "Use Redmark"
        Me.useRedMark.Size = New System.Drawing.Size(303, 20)
        Me.useRedMark.StyleController = Me.LayoutControl5
        Me.useRedMark.TabIndex = 8
        '
        'showClassPostion
        '
        Me.showClassPostion.EditValue = True
        Me.showClassPostion.Location = New System.Drawing.Point(147, 204)
        Me.showClassPostion.Name = "showClassPostion"
        Me.showClassPostion.Properties.Caption = "Show student position in report"
        Me.showClassPostion.Size = New System.Drawing.Size(303, 20)
        Me.showClassPostion.StyleController = Me.LayoutControl5
        Me.showClassPostion.TabIndex = 12
        '
        'txt_redMark_percentage
        '
        Me.txt_redMark_percentage.EditValue = 0
        Me.txt_redMark_percentage.Location = New System.Drawing.Point(141, 138)
        Me.txt_redMark_percentage.Name = "txt_redMark_percentage"
        Me.txt_redMark_percentage.Properties.Appearance.Font = New System.Drawing.Font("Tahoma", 10.0!)
        Me.txt_redMark_percentage.Properties.Appearance.Options.UseFont = True
        Me.txt_redMark_percentage.Properties.Mask.EditMask = "P0"
        Me.txt_redMark_percentage.Properties.Mask.MaskType = DevExpress.XtraEditors.Mask.MaskType.Numeric
        Me.txt_redMark_percentage.Size = New System.Drawing.Size(462, 38)
        Me.txt_redMark_percentage.StyleController = Me.LayoutControl5
        Me.txt_redMark_percentage.TabIndex = 4
        '
        'txt_textsscore_
        '
        Me.txt_textsscore_.EditValue = 0
        Me.txt_textsscore_.Location = New System.Drawing.Point(141, 54)
        Me.txt_textsscore_.Name = "txt_textsscore_"
        Me.txt_textsscore_.Properties.Appearance.Font = New System.Drawing.Font("Tahoma", 10.0!)
        Me.txt_textsscore_.Properties.Appearance.Options.UseFont = True
        Me.txt_textsscore_.Size = New System.Drawing.Size(462, 38)
        Me.txt_textsscore_.StyleController = Me.LayoutControl5
        Me.txt_textsscore_.TabIndex = 6
        '
        'txtexamScore
        '
        Me.txtexamScore.EditValue = 0
        Me.txtexamScore.Location = New System.Drawing.Point(141, 96)
        Me.txtexamScore.Name = "txtexamScore"
        Me.txtexamScore.Properties.Appearance.Font = New System.Drawing.Font("Tahoma", 10.0!)
        Me.txtexamScore.Properties.Appearance.Options.UseFont = True
        Me.txtexamScore.Size = New System.Drawing.Size(462, 38)
        Me.txtexamScore.StyleController = Me.LayoutControl5
        Me.txtexamScore.TabIndex = 5
        '
        'txt_assScore
        '
        Me.txt_assScore.EditValue = 0
        Me.txt_assScore.Location = New System.Drawing.Point(141, 12)
        Me.txt_assScore.Name = "txt_assScore"
        Me.txt_assScore.Properties.Appearance.Font = New System.Drawing.Font("Tahoma", 10.0!)
        Me.txt_assScore.Properties.Appearance.Options.UseFont = True
        Me.txt_assScore.Size = New System.Drawing.Size(462, 38)
        Me.txt_assScore.StyleController = Me.LayoutControl5
        Me.txt_assScore.TabIndex = 4
        '
        'LayoutControlGroup5
        '
        Me.LayoutControlGroup5.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.[True]
        Me.LayoutControlGroup5.GroupBordersVisible = False
        Me.LayoutControlGroup5.Items.AddRange(New DevExpress.XtraLayout.BaseLayoutItem() {Me.LayoutControlItem19, Me.LayoutControlItem20, Me.txt_testScore, Me.LayoutControlItem1, Me.EmptySpaceItem9, Me.LayoutControlItem21, Me.LayoutControlItem24, Me.EmptySpaceItem10, Me.LayoutControlItem28})
        Me.LayoutControlGroup5.Name = "Root"
        Me.LayoutControlGroup5.Size = New System.Drawing.Size(615, 394)
        Me.LayoutControlGroup5.TextVisible = False
        '
        'LayoutControlItem19
        '
        Me.LayoutControlItem19.AppearanceItemCaption.Font = New System.Drawing.Font("Tahoma", 10.0!)
        Me.LayoutControlItem19.AppearanceItemCaption.Options.UseFont = True
        Me.LayoutControlItem19.Control = Me.txt_assScore
        Me.LayoutControlItem19.Location = New System.Drawing.Point(0, 0)
        Me.LayoutControlItem19.Name = "LayoutControlItem19"
        Me.LayoutControlItem19.Size = New System.Drawing.Size(595, 42)
        Me.LayoutControlItem19.Text = "Assignment Score"
        Me.LayoutControlItem19.TextSize = New System.Drawing.Size(117, 16)
        '
        'LayoutControlItem20
        '
        Me.LayoutControlItem20.AppearanceItemCaption.Font = New System.Drawing.Font("Tahoma", 10.0!)
        Me.LayoutControlItem20.AppearanceItemCaption.Options.UseFont = True
        Me.LayoutControlItem20.Control = Me.txtexamScore
        Me.LayoutControlItem20.Location = New System.Drawing.Point(0, 84)
        Me.LayoutControlItem20.Name = "LayoutControlItem20"
        Me.LayoutControlItem20.Size = New System.Drawing.Size(595, 42)
        Me.LayoutControlItem20.Text = "Exam score"
        Me.LayoutControlItem20.TextSize = New System.Drawing.Size(117, 16)
        '
        'txt_testScore
        '
        Me.txt_testScore.AppearanceItemCaption.Font = New System.Drawing.Font("Tahoma", 10.0!)
        Me.txt_testScore.AppearanceItemCaption.Options.UseFont = True
        Me.txt_testScore.Control = Me.txt_textsscore_
        Me.txt_testScore.Location = New System.Drawing.Point(0, 42)
        Me.txt_testScore.Name = "txt_testScore"
        Me.txt_testScore.Size = New System.Drawing.Size(595, 42)
        Me.txt_testScore.Text = "TestScore"
        Me.txt_testScore.TextSize = New System.Drawing.Size(117, 16)
        '
        'LayoutControlItem28
        '
        Me.LayoutControlItem28.Control = Me.showClassPostion
        Me.LayoutControlItem28.Location = New System.Drawing.Point(135, 192)
        Me.LayoutControlItem28.Name = "LayoutControlItem28"
        Me.LayoutControlItem28.Size = New System.Drawing.Size(307, 24)
        Me.LayoutControlItem28.TextSize = New System.Drawing.Size(0, 0)
        Me.LayoutControlItem28.TextVisible = False
        '
        'LayoutControlItem1
        '
        Me.LayoutControlItem1.Control = Me.txt_redMark_percentage
        Me.LayoutControlItem1.Location = New System.Drawing.Point(0, 126)
        Me.LayoutControlItem1.Name = "LayoutControlItem1"
        Me.LayoutControlItem1.Size = New System.Drawing.Size(595, 42)
        Me.LayoutControlItem1.Text = "Percentage for red mark"
        Me.LayoutControlItem1.TextSize = New System.Drawing.Size(117, 13)
        '
        'LayoutControlItem21
        '
        Me.LayoutControlItem21.Control = Me.useRedMark
        Me.LayoutControlItem21.Location = New System.Drawing.Point(135, 168)
        Me.LayoutControlItem21.Name = "LayoutControlItem21"
        Me.LayoutControlItem21.Size = New System.Drawing.Size(307, 24)
        Me.LayoutControlItem21.TextSize = New System.Drawing.Size(0, 0)
        Me.LayoutControlItem21.TextVisible = False
        '
        'LayoutControlItem24
        '
        Me.LayoutControlItem24.Control = Me.chkBoxShowScoreMaxOnSheet
        Me.LayoutControlItem24.Location = New System.Drawing.Point(135, 216)
        Me.LayoutControlItem24.Name = "LayoutControlItem24"
        Me.LayoutControlItem24.Size = New System.Drawing.Size(307, 158)
        Me.LayoutControlItem24.TextSize = New System.Drawing.Size(0, 0)
        Me.LayoutControlItem24.TextVisible = False
        '
        'LayoutControlGroup2
        '
        Me.LayoutControlGroup2.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.[True]
        Me.LayoutControlGroup2.GroupBordersVisible = False
        Me.LayoutControlGroup2.Items.AddRange(New DevExpress.XtraLayout.BaseLayoutItem() {Me.LayoutControlItem6, Me.LayoutControlItem15, Me.EmptySpaceItem12, Me.EmptySpaceItem11})
        Me.LayoutControlGroup2.Name = "Root"
        Me.LayoutControlGroup2.Size = New System.Drawing.Size(981, 517)
        Me.LayoutControlGroup2.TextVisible = False
        '
        'LayoutControlItem6
        '
        Me.LayoutControlItem6.Control = Me.GroupControl1
        Me.LayoutControlItem6.Location = New System.Drawing.Point(92, 74)
        Me.LayoutControlItem6.Name = "LayoutControlItem6"
        Me.LayoutControlItem6.Size = New System.Drawing.Size(623, 423)
        Me.LayoutControlItem6.TextSize = New System.Drawing.Size(0, 0)
        Me.LayoutControlItem6.TextVisible = False
        '
        'LayoutControlItem15
        '
        Me.LayoutControlItem15.Control = Me.GroupControl3
        Me.LayoutControlItem15.Location = New System.Drawing.Point(92, 0)
        Me.LayoutControlItem15.Name = "LayoutControlItem15"
        Me.LayoutControlItem15.Size = New System.Drawing.Size(623, 74)
        Me.LayoutControlItem15.TextSize = New System.Drawing.Size(0, 0)
        Me.LayoutControlItem15.TextVisible = False
        '
        'EmptySpaceItem12
        '
        Me.EmptySpaceItem12.AllowHotTrack = False
        Me.EmptySpaceItem12.Location = New System.Drawing.Point(715, 0)
        Me.EmptySpaceItem12.Name = "EmptySpaceItem12"
        Me.EmptySpaceItem12.Size = New System.Drawing.Size(246, 497)
        Me.EmptySpaceItem12.TextSize = New System.Drawing.Size(0, 0)
        '
        'EmptySpaceItem11
        '
        Me.EmptySpaceItem11.AllowHotTrack = False
        Me.EmptySpaceItem11.Location = New System.Drawing.Point(0, 0)
        Me.EmptySpaceItem11.Name = "EmptySpaceItem11"
        Me.EmptySpaceItem11.Size = New System.Drawing.Size(92, 497)
        Me.EmptySpaceItem11.TextSize = New System.Drawing.Size(0, 0)
        '
        'NavigationPage3
        '
        Me.NavigationPage3.Caption = "NavigationPage3"
        Me.NavigationPage3.Name = "NavigationPage3"
        Me.NavigationPage3.Size = New System.Drawing.Size(981, 517)
        '
        'WindowsUIButtonPanel1
        '
        Me.WindowsUIButtonPanel1.AllowGlyphSkinning = False
        Me.WindowsUIButtonPanel1.AppearanceButton.Hovered.BackColor = System.Drawing.Color.FromArgb(CType(CType(130, Byte), Integer), CType(CType(130, Byte), Integer), CType(CType(130, Byte), Integer))
        Me.WindowsUIButtonPanel1.AppearanceButton.Hovered.FontSizeDelta = -1
        Me.WindowsUIButtonPanel1.AppearanceButton.Hovered.ForeColor = System.Drawing.Color.FromArgb(CType(CType(130, Byte), Integer), CType(CType(130, Byte), Integer), CType(CType(130, Byte), Integer))
        Me.WindowsUIButtonPanel1.AppearanceButton.Hovered.Options.UseBackColor = True
        Me.WindowsUIButtonPanel1.AppearanceButton.Hovered.Options.UseFont = True
        Me.WindowsUIButtonPanel1.AppearanceButton.Hovered.Options.UseForeColor = True
        Me.WindowsUIButtonPanel1.AppearanceButton.Normal.FontSizeDelta = -1
        Me.WindowsUIButtonPanel1.AppearanceButton.Normal.Options.UseFont = True
        Me.WindowsUIButtonPanel1.AppearanceButton.Pressed.BackColor = System.Drawing.Color.FromArgb(CType(CType(159, Byte), Integer), CType(CType(159, Byte), Integer), CType(CType(159, Byte), Integer))
        Me.WindowsUIButtonPanel1.AppearanceButton.Pressed.FontSizeDelta = -1
        Me.WindowsUIButtonPanel1.AppearanceButton.Pressed.ForeColor = System.Drawing.Color.FromArgb(CType(CType(159, Byte), Integer), CType(CType(159, Byte), Integer), CType(CType(159, Byte), Integer))
        Me.WindowsUIButtonPanel1.AppearanceButton.Pressed.Options.UseBackColor = True
        Me.WindowsUIButtonPanel1.AppearanceButton.Pressed.Options.UseFont = True
        Me.WindowsUIButtonPanel1.AppearanceButton.Pressed.Options.UseForeColor = True
        Me.WindowsUIButtonPanel1.BackColor = System.Drawing.Color.FromArgb(CType(CType(63, Byte), Integer), CType(CType(63, Byte), Integer), CType(CType(63, Byte), Integer))
        Me.WindowsUIButtonPanel1.ButtonInterval = 40
        WindowsUIButtonImageOptions10.Image = CType(resources.GetObject("WindowsUIButtonImageOptions10.Image"), System.Drawing.Image)
        Me.WindowsUIButtonPanel1.Buttons.AddRange(New DevExpress.XtraEditors.ButtonPanel.IBaseButton() {New DevExpress.XtraBars.Docking2010.WindowsUIButton("Save all data", True, WindowsUIButtonImageOptions10, DevExpress.XtraBars.Docking2010.ButtonStyle.PushButton, "Save all data", 1, True, Nothing, True, False, True, Nothing, -1, False)})
        Me.WindowsUIButtonPanel1.Dock = System.Windows.Forms.DockStyle.Bottom
        Me.WindowsUIButtonPanel1.EnableImageTransparency = True
        Me.WindowsUIButtonPanel1.ForeColor = System.Drawing.Color.White
        Me.WindowsUIButtonPanel1.Location = New System.Drawing.Point(0, 577)
        Me.WindowsUIButtonPanel1.Margin = New System.Windows.Forms.Padding(4, 5, 4, 5)
        Me.WindowsUIButtonPanel1.MaximumSize = New System.Drawing.Size(0, 60)
        Me.WindowsUIButtonPanel1.MinimumSize = New System.Drawing.Size(60, 60)
        Me.WindowsUIButtonPanel1.Name = "WindowsUIButtonPanel1"
        Me.WindowsUIButtonPanel1.Size = New System.Drawing.Size(981, 60)
        Me.WindowsUIButtonPanel1.TabIndex = 17
        Me.WindowsUIButtonPanel1.Text = "WindowsUIButtonPanel1"
        Me.WindowsUIButtonPanel1.UseButtonBackgroundImages = False
        '
        'EmptySpaceItem9
        '
        Me.EmptySpaceItem9.AllowHotTrack = False
        Me.EmptySpaceItem9.Location = New System.Drawing.Point(0, 168)
        Me.EmptySpaceItem9.Name = "EmptySpaceItem9"
        Me.EmptySpaceItem9.Size = New System.Drawing.Size(135, 206)
        Me.EmptySpaceItem9.TextSize = New System.Drawing.Size(0, 0)
        '
        'EmptySpaceItem10
        '
        Me.EmptySpaceItem10.AllowHotTrack = False
        Me.EmptySpaceItem10.Location = New System.Drawing.Point(442, 168)
        Me.EmptySpaceItem10.Name = "EmptySpaceItem10"
        Me.EmptySpaceItem10.Size = New System.Drawing.Size(153, 206)
        Me.EmptySpaceItem10.TextSize = New System.Drawing.Size(0, 0)
        '
        'NavigationPage4
        '
        Me.NavigationPage4.Name = "NavigationPage4"
        Me.NavigationPage4.Size = New System.Drawing.Size(981, 517)
        '
        'settingsView
        '
        Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 13.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.Controls.Add(Me.NavigationFrame1)
        Me.Controls.Add(Me.WindowsUIButtonPanel1)
        Me.Controls.Add(Me.windowsUIButtonPanelMain)
        Me.LookAndFeel.TouchUIMode = DevExpress.Utils.DefaultBoolean.[True]
        Me.Name = "settingsView"
        Me.Size = New System.Drawing.Size(981, 637)
        CType(Me.NavigationFrame1, System.ComponentModel.ISupportInitialize).EndInit()
        Me.NavigationFrame1.ResumeLayout(False)
        Me.NavigationPage1.ResumeLayout(False)
        CType(Me.LayoutControl1, System.ComponentModel.ISupportInitialize).EndInit()
        Me.LayoutControl1.ResumeLayout(False)
        CType(Me.sch_name_tb.Properties, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.sch_address_tb.Properties, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.sch_motto_tb.Properties, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.sch_email_tb.Properties, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.sch_contact_no_tb.Properties, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.sch_logo_picedit.Properties, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.sch_website_tb.Properties, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.Sch_facebook_tb.Properties, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.sch_twitter_tb.Properties, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.sch_linkedIn_tb.Properties, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.LayoutControlGroup1, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.Root1, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.Root2, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.Root3, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.LayoutControlItem2, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.LayoutControlItem5, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.LayoutControlItem10, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.LayoutControlItem12, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.EmptySpaceItem4, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.LayoutControlItem13, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.EmptySpaceItem5, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.EmptySpaceItem19, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.EmptySpaceItem20, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.EmptySpaceItem21, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.LayoutControlItem4, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.LayoutControlItem3, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.Root4, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.Root5, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.Root6, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.LayoutControlItem7, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.LayoutControlItem9, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.LayoutControlItem11, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.LayoutControlItem14, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.EmptySpaceItem8, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.autoGeneratedGroup1, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.EmptySpaceItem2, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.autoGeneratedGroup0, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.EmptySpaceItem7, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.EmptySpaceItem1, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.EmptySpaceItem3, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.EmptySpaceItem6, System.ComponentModel.ISupportInitialize).EndInit()
        Me.NavigationPage2.ResumeLayout(False)
        CType(Me.LayoutControl2, System.ComponentModel.ISupportInitialize).EndInit()
        Me.LayoutControl2.ResumeLayout(False)
        CType(Me.GroupControl3, System.ComponentModel.ISupportInitialize).EndInit()
        Me.GroupControl3.ResumeLayout(False)
        CType(Me.LayoutControl4, System.ComponentModel.ISupportInitialize).EndInit()
        Me.LayoutControl4.ResumeLayout(False)
        CType(Me.idNoInitial.Properties, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.LayoutControlGroup4, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.LayoutControlItem22, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.GroupControl1, System.ComponentModel.ISupportInitialize).EndInit()
        Me.GroupControl1.ResumeLayout(False)
        CType(Me.LayoutControl5, System.ComponentModel.ISupportInitialize).EndInit()
        Me.LayoutControl5.ResumeLayout(False)
        CType(Me.chkBoxShowScoreMaxOnSheet.Properties, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.useRedMark.Properties, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.showClassPostion.Properties, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.txt_redMark_percentage.Properties, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.txt_textsscore_.Properties, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.txtexamScore.Properties, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.txt_assScore.Properties, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.LayoutControlGroup5, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.LayoutControlItem19, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.LayoutControlItem20, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.txt_testScore, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.LayoutControlItem28, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.LayoutControlItem1, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.LayoutControlItem21, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.LayoutControlItem24, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.LayoutControlGroup2, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.LayoutControlItem6, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.LayoutControlItem15, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.EmptySpaceItem12, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.EmptySpaceItem11, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.EmptySpaceItem9, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.EmptySpaceItem10, System.ComponentModel.ISupportInitialize).EndInit()
        Me.ResumeLayout(False)

    End Sub

    Private WithEvents windowsUIButtonPanelMain As DevExpress.XtraBars.Docking2010.WindowsUIButtonPanel
    Friend WithEvents NavigationFrame1 As DevExpress.XtraBars.Navigation.NavigationFrame
    Friend WithEvents NavigationPage1 As DevExpress.XtraBars.Navigation.NavigationPage
    Friend WithEvents LayoutControl1 As DevExpress.XtraLayout.LayoutControl
    Friend WithEvents sch_name_tb As DevExpress.XtraEditors.TextEdit
    Friend WithEvents sch_address_tb As DevExpress.XtraEditors.MemoEdit
    Friend WithEvents sch_motto_tb As DevExpress.XtraEditors.TextEdit
    Friend WithEvents sch_email_tb As DevExpress.XtraEditors.TextEdit
    Friend WithEvents sch_contact_no_tb As DevExpress.XtraEditors.TextEdit
    Friend WithEvents sch_logo_picedit As DevExpress.XtraEditors.PictureEdit
    Friend WithEvents LayoutControlGroup1 As DevExpress.XtraLayout.LayoutControlGroup
    Friend WithEvents Root1 As DevExpress.XtraLayout.LayoutControlGroup
    Friend WithEvents Root2 As DevExpress.XtraLayout.LayoutControlGroup
    Friend WithEvents Root3 As DevExpress.XtraLayout.LayoutControlGroup
    Friend WithEvents LayoutControlItem2 As DevExpress.XtraLayout.LayoutControlItem
    Friend WithEvents LayoutControlItem3 As DevExpress.XtraLayout.LayoutControlItem
    Friend WithEvents LayoutControlItem4 As DevExpress.XtraLayout.LayoutControlItem
    Friend WithEvents LayoutControlItem5 As DevExpress.XtraLayout.LayoutControlItem
    Friend WithEvents LayoutControlItem10 As DevExpress.XtraLayout.LayoutControlItem
    Friend WithEvents LayoutControlItem12 As DevExpress.XtraLayout.LayoutControlItem
    Friend WithEvents EmptySpaceItem4 As DevExpress.XtraLayout.EmptySpaceItem
    Friend WithEvents EmptySpaceItem5 As DevExpress.XtraLayout.EmptySpaceItem
    Friend WithEvents EmptySpaceItem19 As DevExpress.XtraLayout.EmptySpaceItem
    Friend WithEvents EmptySpaceItem20 As DevExpress.XtraLayout.EmptySpaceItem
    Friend WithEvents EmptySpaceItem21 As DevExpress.XtraLayout.EmptySpaceItem
    Friend WithEvents autoGeneratedGroup0 As DevExpress.XtraLayout.LayoutControlGroup
    Friend WithEvents EmptySpaceItem2 As DevExpress.XtraLayout.EmptySpaceItem
    Friend WithEvents EmptySpaceItem1 As DevExpress.XtraLayout.EmptySpaceItem
    Friend WithEvents EmptySpaceItem3 As DevExpress.XtraLayout.EmptySpaceItem
    Friend WithEvents EmptySpaceItem6 As DevExpress.XtraLayout.EmptySpaceItem
    Friend WithEvents NavigationPage2 As DevExpress.XtraBars.Navigation.NavigationPage
    'Friend WithEvents Sfms_dbDataSet As result_db1DataSet
    ' Friend WithEvents Sch_setupTableAdapter As sfms_dbDataSetTableAdapters.sch_setupTableAdapter
    Friend WithEvents SimpleButton1 As DevExpress.XtraEditors.SimpleButton
    Friend WithEvents sch_website_tb As DevExpress.XtraEditors.TextEdit
    Friend WithEvents Sch_facebook_tb As DevExpress.XtraEditors.TextEdit
    Friend WithEvents sch_twitter_tb As DevExpress.XtraEditors.TextEdit
    Friend WithEvents sch_linkedIn_tb As DevExpress.XtraEditors.TextEdit
    Friend WithEvents LayoutControlItem13 As DevExpress.XtraLayout.LayoutControlItem
    Friend WithEvents Root4 As DevExpress.XtraLayout.LayoutControlGroup
    Friend WithEvents Root5 As DevExpress.XtraLayout.LayoutControlGroup
    Friend WithEvents Root6 As DevExpress.XtraLayout.LayoutControlGroup
    Friend WithEvents LayoutControlItem7 As DevExpress.XtraLayout.LayoutControlItem
    Friend WithEvents LayoutControlItem9 As DevExpress.XtraLayout.LayoutControlItem
    Friend WithEvents LayoutControlItem11 As DevExpress.XtraLayout.LayoutControlItem
    Friend WithEvents LayoutControlItem14 As DevExpress.XtraLayout.LayoutControlItem
    Friend WithEvents EmptySpaceItem8 As DevExpress.XtraLayout.EmptySpaceItem
    Friend WithEvents autoGeneratedGroup1 As DevExpress.XtraLayout.LayoutControlGroup
    Friend WithEvents EmptySpaceItem7 As DevExpress.XtraLayout.EmptySpaceItem
    Friend WithEvents LayoutControl2 As DevExpress.XtraLayout.LayoutControl
    Friend WithEvents GroupControl3 As DevExpress.XtraEditors.GroupControl
    Friend WithEvents LayoutControl4 As DevExpress.XtraLayout.LayoutControl
    Friend WithEvents LayoutControlGroup4 As DevExpress.XtraLayout.LayoutControlGroup
    Friend WithEvents GroupControl1 As DevExpress.XtraEditors.GroupControl
    Friend WithEvents LayoutControl5 As DevExpress.XtraLayout.LayoutControl
    Friend WithEvents LayoutControlGroup5 As DevExpress.XtraLayout.LayoutControlGroup
    Friend WithEvents LayoutControlGroup2 As DevExpress.XtraLayout.LayoutControlGroup
    Friend WithEvents LayoutControlItem6 As DevExpress.XtraLayout.LayoutControlItem
    Friend WithEvents LayoutControlItem15 As DevExpress.XtraLayout.LayoutControlItem
    Private WithEvents WindowsUIButtonPanel1 As DevExpress.XtraBars.Docking2010.WindowsUIButtonPanel
    Friend WithEvents EmptySpaceItem11 As DevExpress.XtraLayout.EmptySpaceItem
    Friend WithEvents EmptySpaceItem12 As DevExpress.XtraLayout.EmptySpaceItem
    'Friend WithEvents Sch_setupTableAdapter As result_db1DataSetTableAdapters.sch_setupTableAdapter
    'Friend WithEvents Result_db1DataSet As result_db1DataSet
    Friend WithEvents txt_textsscore_ As DevExpress.XtraEditors.TextEdit
    Friend WithEvents txtexamScore As DevExpress.XtraEditors.TextEdit
    Friend WithEvents txt_assScore As DevExpress.XtraEditors.TextEdit
    Friend WithEvents LayoutControlItem19 As DevExpress.XtraLayout.LayoutControlItem
    Friend WithEvents LayoutControlItem20 As DevExpress.XtraLayout.LayoutControlItem
    Friend WithEvents txt_testScore As DevExpress.XtraLayout.LayoutControlItem
    'Friend WithEvents Result_db1DataSet1 As result_db1DataSet
    'Friend WithEvents Sch_setupTableAdapter1 As result_db1DataSetTableAdapters.sch_setupTableAdapter
    Friend WithEvents NavigationPage3 As DevExpress.XtraBars.Navigation.NavigationPage
    Friend WithEvents txt_redMark_percentage As DevExpress.XtraEditors.TextEdit
    Friend WithEvents useRedMark As DevExpress.XtraEditors.CheckEdit
    Friend WithEvents showClassPostion As DevExpress.XtraEditors.CheckEdit
    Friend WithEvents LayoutControlItem28 As DevExpress.XtraLayout.LayoutControlItem
    Friend WithEvents LayoutControlItem1 As DevExpress.XtraLayout.LayoutControlItem
    Friend WithEvents LayoutControlItem21 As DevExpress.XtraLayout.LayoutControlItem
    Friend WithEvents idNoInitial As DevExpress.XtraEditors.TextEdit
    Friend WithEvents LayoutControlItem22 As DevExpress.XtraLayout.LayoutControlItem
    Friend WithEvents chkBoxShowScoreMaxOnSheet As DevExpress.XtraEditors.CheckEdit
    Friend WithEvents LayoutControlItem24 As DevExpress.XtraLayout.LayoutControlItem
    Friend WithEvents EmptySpaceItem9 As DevExpress.XtraLayout.EmptySpaceItem
    Friend WithEvents EmptySpaceItem10 As DevExpress.XtraLayout.EmptySpaceItem
    Friend WithEvents NavigationPage4 As DevExpress.XtraBars.Navigation.NavigationPage
End Class
